version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
