//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UKControllerPlugin.rc
//
#define IDR_WAVE1                       101
#define IDD_DIALOG1                     102
#define IDD_HISTORY_TRAIL               102
#define IDD_DIALOG2                     106
#define IDD_GENERAL_SETTINGS            106
#define HOLD_SELECTOR_DIALOG            109
#define IDD_TIMER_CONFIGURATION         111
#define IDD_MINSTACK                    113
#define IDD_MINSTACK1                   114
#define IDD_REGIONAL_PRESSURE           114
#define IDD_SRD_SEARCH                  115
#define IDC_CHECK_DEGRADING             1001
#define IDC_CHECK_FADING                1002
#define IDC_CHECK_AA                    1003
#define IDC_TRAIL_TYPE                  1004
#define IDC_TRAIL_LENGTH                1005
#define IDC_TRAIL_COLOUR                1009
#define IDC_SPIN_LENGTH                 1010
#define IDC_DOT_SIZE                    1012
#define GS_DIALOG_PRENOTE_TITLE         1012
#define IDC_DOT_SIZE_SPIN               1013
#define IDC_CHECK1                      1013
#define GS_DIALOG_PRENOTE_CHECK         1013
#define TIMER1_ENABLED_CHECK            1013
#define IDC_MINSTACK_DISPLAY_CHECK      1013
#define TIMER2_ENABLED_CHECK            1014
#define IDC_MFCBUTTON1                  1015
#define TIMER3_ENABLED_CHECK            1015
#define IDC_MAX_FILTER_TEXT             1016
#define TIMER4_ENABLED_CHECK            1016
#define IDC_MAX_FILTER_SPIN             1017
#define TIMER5_ENABLED_CHECK            1017
#define IDC_FILTER_MAX_LABEL            1018
#define IDC_MAX_FILTER_LABEL            1018
#define HOLD_PROFILE_NAME_EDIT          1018
#define IDC_HOLD_PROFILE_NAME_EDIT      1018
#define IDC_SRD_ORIGIN                  1018
#define IDC_MIN_FILTER_TEXT             1019
#define IDC_MIN_FILTER_SPIN             1020
#define IDC_MIN_FILTER_LABEL            1021
#define GS_DIALOG_IA_CHECK              1022
#define GS_DIALOG_SQUAWK_CHECK          1023
#define IDC_HOLD_PROFILE_SELECT         1024
#define GS_QNH_CHANGE_CHECK             1024
#define GS_DIALOG_QNH_CHECK             1024
#define IDC_HOLD_PROFILE_SELECT_LABEL   1025
#define IDC_HOLD_SELECT_LOAD            1026
#define IDC_HOLD_SELECT_DISPLAY         1026
#define IDC_HOLD_SELECT_SAVE            1027
#define IDC_HOLD_PROFILE_UPDATE         1027
#define IDC_COMBO3                      1030
#define IDC_HOLD_SELECTOR               1030
#define IDC_HOLD_OPEN                   1031
#define IDC_HOLD_ADD                    1031
#define IDC_BUTTON4                     1032
#define IDC_MINSTACK_ADD                1032
#define HOLD_SELECTOR_OK                1033
#define IDC_LIST1                       1034
#define IDC_HOLD_PROFILE_LIST           1034
#define IDC_MINSTACK_LIST               1034
#define IDC_HOLD_REMOVE                 1035
#define IDC_HOLD_LIST                   1036
#define IDC_HOLD_PROFILE_STATIC         1037
#define IDC_HOLD_SELECT_LABEL           1039
#define IDC_HOLD_PROFILE_LABEL          1040
#define IDC_HOLD_PROFILE_NEW            1041
#define IDC_HOLD_PROFILE_DELETE         1042
#define HOLD_PROFILE_NAME_STATIC        1044
#define IDC_BUTTON2                     1046
#define TIMER1_EDIT_DURATION            1047
#define TIMER2_EDIT_DURATION            1048
#define IDC_TIME_FORMAT_CHECK           1048
#define TIMER3_EDIT_DURATION            1049
#define GS_TIME_FORMAT_CHECK            1049
#define TIMER4_EDIT_DURATION            1050
#define TIMER5_EDIT_VALUE               1051
#define TIMER5_EDIT_DURATION            1051
#define TIMER1_LABEL                    1052
#define TIMER_CONFIG_ENABLED_LABEL      1053
#define TIMER_CONFIG_DURATION_LABEL     1054
#define TIMER2_LABEL                    1055
#define TIMER3_LABEL                    1056
#define TIMER4_LABEL                    1057
#define TIMER5_LABEL                    1058
#define IDC_MINSTACK_DELETE             1060
#define IDC_MINSTACK_DOWN               1061
#define IDC_MINSTACK_UP                 1062
#define IDC_COMBO2                      1064
#define IDC_MINSTACK_SELECT             1064
#define IDC_MINSTACK_SELECTED_LABEL     1065
#define IDC_RPS_DISPLAY_CHECK           1066
#define IDC_RPS_SELECTED_LABEL          1067
#define IDC_RPS_LIST                    1068
#define IDC_RPS_UP                      1069
#define IDC_RPS_DOWN                    1070
#define IDC_RPS_DELETE                  1071
#define IDC_RPS_SELECT                  1072
#define IDC_RPS_ADD                     1073
#define IDC_SRD_ORIGIN_STATIC           1075
#define IDC_SRD_DESTINATION             1076
#define IDC_SRD_CRUISE                  1078
#define IDC_STATIC_REQUIRED             1079
#define IDC_SRD_CRUISE_STATIC           1080
#define IDC_SRD_DESTINATION_STATIC      1081
#define IDC_LIST4                       1085
#define IDC_SRD_RESULTS                 1085

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
