//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UKControllerPlugin.rc
//
#define ISOLATION_AWARE_ENABLED         1
#define IDR_WAVE1                       101
#define IDD_DIALOG1                     102
#define IDD_HISTORY_TRAIL               102
#define IDD_DIALOG2                     106
#define IDD_GENERAL_SETTINGS            106
#define IDD_TIMER_CONFIGURATION         111
#define IDD_MINSTACK                    113
#define IDD_MINSTACK1                   114
#define IDD_REGIONAL_PRESSURE           114
#define IDD_SRD_SEARCH                  115
#define IDD_HOLD_PARAMS                 117
#define IDD_HOLD_SELECTION              119
#define IDD_NOTIFICATIONS               121
#define IDD_OCEANIC_CLEARANCE           125
#define IDD_DEPARTURE_RELEASE_REQUEST   127
#define IDD_DEPARTURE_RELEASE_APPROVE   129
#define WAVE_DEP_RLS_ACCEPT             131
#define WAVE_DEP_RLS_REJ                132
#define WAVE_DEP_RLS_REQ                133
#define IDR_NEW_PRENOTE                 135
#define WAVE_NEW_PRENOTE                135
#define IDR_WAVE2                       136
#define WAVE_MISSED_APPROACH            136
#define IDD_MISSED_APPROACH             137
#define IDD_MISSED_APPROACH_ACKNOWLEDGE 139
#define IDD_DEPARTURE_RELEASE_REJECT    141
#define IDD_API_KEY_REPLACE             143
#define IDC_CHECK_DEGRADING             1001
#define IDC_CHECK_FADING                1002
#define IDC_CHECK_AA                    1003
#define IDC_TRAIL_TYPE                  1004
#define IDC_TRAIL_LENGTH                1005
#define IDC_TRAIL_COLOUR                1009
#define IDC_SPIN_LENGTH                 1010
#define IDC_DOT_SIZE                    1012
#define GS_DIALOG_PRENOTE_TITLE         1012
#define IDC_DOT_SIZE_SPIN               1013
#define IDC_CHECK1                      1013
#define GS_DIALOG_PRENOTE_CHECK         1013
#define TIMER1_ENABLED_CHECK            1013
#define IDC_MINSTACK_DISPLAY_CHECK      1013
#define MISSED_APPROACH_PLAY_SOUND      1013
#define TIMER2_ENABLED_CHECK            1014
#define IDC_MFCBUTTON1                  1015
#define TIMER3_ENABLED_CHECK            1015
#define IDC_MAX_FILTER_TEXT             1016
#define TIMER4_ENABLED_CHECK            1016
#define IDC_MAX_FILTER_SPIN             1017
#define TIMER5_ENABLED_CHECK            1017
#define IDC_FILTER_MAX_LABEL            1018
#define IDC_MAX_FILTER_LABEL            1018
#define HOLD_PROFILE_NAME_EDIT          1018
#define IDC_SRD_ORIGIN                  1018
#define IDC_HOLD_MINIMUM                1018
#define IDC_MIN_FILTER_TEXT             1019
#define IDC_MIN_FILTER_SPIN             1020
#define IDC_MIN_FILTER_LABEL            1021
#define GS_DIALOG_IA_CHECK              1022
#define GS_DIALOG_SQUAWK_CHECK          1023
#define IDC_HOLD_PROFILE_SELECT         1024
#define GS_QNH_CHANGE_CHECK             1024
#define GS_DIALOG_QNH_CHECK             1024
#define IDC_HOLD_PROFILE_SELECT_LABEL   1025
#define GS_DIALOG_IA_CHECK2             1025
#define GS_DIALOG_IH_CHECK              1025
#define IDC_HOLD_SELECT_LOAD            1026
#define IDC_HOLD_SELECT_SAVE            1027
#define IDC_COMBO3                      1030
#define IDC_HOLD_OPEN                   1031
#define IDC_BUTTON4                     1032
#define IDC_MINSTACK_ADD                1032
#define IDC_LIST1                       1034
#define IDC_MINSTACK_LIST               1034
#define IDC_NOTIFICATIONS_LIST          1034
#define MISSED_APPROACH_SOUND_SERVICE_LIST 1034
#define MISSED_APPROACH_SERVICE_LIST    1034
#define IDC_HOLD_LIST                   1036
#define IDC_BUTTON2                     1046
#define IDC_ROUTE_COPY                  1046
#define IDC_SRD_ROUTE_COPY              1046
#define IDC_HOLD_CLOSE                  1046
#define IDC_API_KEY_REPLACE_CANCEL      1046
#define TIMER1_EDIT_DURATION            1047
#define TIMER2_EDIT_DURATION            1048
#define IDC_TIME_FORMAT_CHECK           1048
#define TIMER3_EDIT_DURATION            1049
#define GS_TIME_FORMAT_CHECK            1049
#define TIMER4_EDIT_DURATION            1050
#define TIMER5_EDIT_VALUE               1051
#define TIMER5_EDIT_DURATION            1051
#define TIMER1_LABEL                    1052
#define TIMER_CONFIG_ENABLED_LABEL      1053
#define TIMER_CONFIG_DURATION_LABEL     1054
#define TIMER2_LABEL                    1055
#define TIMER3_LABEL                    1056
#define TIMER4_LABEL                    1057
#define TIMER5_LABEL                    1058
#define IDC_MINSTACK_DELETE             1060
#define IDC_MINSTACK_DOWN               1061
#define IDC_MINSTACK_UP                 1062
#define IDC_COMBO2                      1064
#define IDC_MINSTACK_SELECT             1064
#define IDC_MINSTACK_SELECTED_LABEL     1065
#define IDC_RPS_DISPLAY_CHECK           1066
#define IDC_RPS_SELECTED_LABEL          1067
#define IDC_RPS_LIST                    1068
#define IDC_RPS_UP                      1069
#define IDC_RPS_DOWN                    1070
#define IDC_RPS_DELETE                  1071
#define IDC_RPS_SELECT                  1072
#define IDC_RPS_ADD                     1073
#define IDC_SRD_ORIGIN_STATIC           1075
#define IDC_SRD_DESTINATION             1076
#define IDC_SRD_CRUISE                  1078
#define IDC_STATIC_REQUIRED             1079
#define IDC_SRD_CRUISE_STATIC           1080
#define IDC_SRD_DESTINATION_STATIC      1081
#define IDC_SRD_RESULTS                 1085
#define IDC_BUTTON1                     1086
#define IDC_SRD_SEARCH                  1086
#define IDC_HOLDS_SAVE                  1086
#define IDC_OPEN_NOTIFICATION           1086
#define IDC_API_REOPEN_BROWSER          1086
#define IDC_EDIT1                       1087
#define IDC_SRD_NOTES                   1087
#define IDC_READ_NOTIFICATION           1087
#define IDC_DEPARTURE_RELEASE_REQUEST_CALLSIGN 1087
#define IDC_DEPARTURE_RELEASE_APPROVE_CALLSIGN 1087
#define MISSED_APPROACH_DRAW_DURATION   1087
#define IDC_RELEASE_REJECT_REMARKS      1087
#define IDC_NOTES_STATIC                1088
#define IDC_HOLD_PARAMS_MIN_STATIC      1089
#define IDC_NOTIFICATION_BODY           1089
#define IDC_HOLD_PARAMS_MAX_STATIC      1090
#define IDC_HOLD_MIN_SPIN               1091
#define IDC_HOLD_MAX                    1092
#define IDC_HOLD_MAXIMUM                1092
#define IDC_SPIN2                       1093
#define IDC_HOLD_MAX_SPIN               1093
#define IDC_NOTIFICATION_LINK           1094
#define IDC_NOTIFICATION_TITLE          1095
#define ID_OK                           1096
#define IDC_OCEANIC_STATIC_CALLSIGN     1097
#define IDC_OCEANIC_STATIC_STATUS       1098
#define IDC_OCEANIC_STATIC_TRACK        1099
#define IDC_OCEANIC_STATIC_FIX          1100
#define IDC_OCEANIC_STATIC_LEVEL        1101
#define IDC_OCEANIC_STATIC_MACH         1102
#define IDC_OCEANIC_STATIC_ENTRY        1103
#define IDC_OCEANIC_STATIC_ISSUED       1104
#define IDC_OCEANIC_STATIC_EXTRA        1105
#define IDC_OCEANIC_STATIC_CALLSIGN_DATA 1106
#define IDC_OCEANIC_STATIC_STATUS_DATA  1107
#define IDC_OCEANIC_STATIC_TRACK_DATA   1108
#define IDC_OCEANIC_STATIC_FIX_DATA     1109
#define IDC_OCEANIC_STATIC_LEVEL_DATA   1110
#define IDC_DEPARTURE_RELEASE_REQUEST_CALLSIGN_STATIC 1110
#define IDC_OCEANIC_STATIC_MACH_DATA    1111
#define IDC_DEPARTURE_RELEASE_TARGET_CONTROLLER 1111
#define IDC_OCEANIC_STATIC_ENTRY_DATA   1112
#define IDC_DEPARTURE_RELEASE_TARGET_CONTROLLER_STATIC 1112
#define IDC_DEPARTURE_RELEASE_APPROVE_CALLSIGN_STATIC 1113
#define IDC_OCEANIC_STATIC_ISSUED_DATA  1114
#define IDC_DEPARTURE_RELEASE_APPROVE_VALIDFOR 1114
#define IDC_OCEANIC_STATIC_ISSUED_DATA2 1115
#define IDC_OCEANIC_STATIC_EXTRA_DATA   1115
#define IDC_DEPARTURE_RELEASE_APPROVE_VALIDFOR_STATIC 1115
#define IDC_DATETIMEPICKER1             1116
#define IDC_DEPARTURE_RELEASE_APPROVE_RELEASED_AT 1116
#define IDC_DEPARTURE_RELEASE_APPROVE_RELEASED_AT_STATIC 1117
#define IDC_CHECK_FILL                  1118
#define IDC_CHECK2                      1119
#define IDC_TRAIL_ROTATE                1119
#define MISSED_APPROACH_SOUND_USER      1119
#define IDC_PRENOTE_CHAT_MESSAGE        1119
#define IDC_SYSLINK2                    1121
#define IDC_SYSLINK3                    1122
#define MISSED_APPROACH_GLOSAL_STATIc   1123
#define MISSED_APPROACH_SOUND_STATIC    1126
#define MISSED_APPROACH_ALERT_STATIC    1126
#define MISSED_APPROACH_ASR_STATIC      1127
#define MISSED_APPROACH_CIRCLE          1128
#define MISSED_APPROACH_LINE            1129
#define MISSED_APPROACH_DRAW_AIRFIELDS  1130
#define MISSED_APPROACH_AIRFIELDS       1130
#define MISSED_APPROACH_DRAW_AIRFIELD_LIST 1132
#define MISSED_APPROACH_AIRFIELD_LIST   1132
#define MISSED_APPROACH_DRAW_PROVISIONS 1133
#define IDC_LIST4                       1134
#define MISSED_APPROACH_DRAW_SERVICE_LIST 1134
#define MISSED_APPROACH_DRAW_DURATION_TEXT 1135
#define IDC_MISSED_APPROACH_REMARKS     1137
#define IDC_MISSED_APPROACH_STATIC      1138
#define IDC_RELEASE_APPROVE_REMARKS     1139
#define IDC_RELEASE_APPROVE_REMARKS_STATIC 1140
#define IDC_RELEASE_REJECT_REMARKS_STATIC 1141
#define IDC_GEN_SETTINGS_EXPERIMENTAL   1142
#define IDC_RELEASE_CHANNEL             1143
#define IDC_API_KEY_STATIC              1144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1145
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
