#include "PersistenceContainer.h"
#include "curl/CurlInterface.h"
#include "windows/WinApiInterface.h"
#include "api/ApiInterface.h"
#include "controller/ActiveCallsignCollection.h"
#include "airfield/AirfieldCollection.h"
#include "ownership/AirfieldOwnershipManager.h"
#include "flightplan/StoredFlightplanCollection.h"
#include "flightplan/FlightPlanEventHandlerCollection.h"
#include "controller/ControllerStatusEventHandlerCollection.h"
#include "euroscope/RadarTargetEventHandlerCollection.h"
#include "timedevent/TimedEventCollection.h"
#include "tag/TagItemCollection.h"
#include "plugin/FunctionCallEventHandler.h"
#include "metar/MetarEventHandlerCollection.h"
#include "plugin/UKPlugin.h"
#include "radarscreen/RadarScreenFactory.h"
#include "initialaltitude/InitialAltitudeEventHandler.h"
#include "historytrail/HistoryTrailRepository.h"
#include "radarscreen/RadarRenderableCollection.h"
#include "radarscreen/ScreenControls.h"
#include "graphics/GdiplusBrushes.h"
#include "graphics/GdiGraphicsWrapper.h"
#include "countdown/CountdownTimer.h"
#include "minstack/MinStackManager.h"
#include "squawk/SquawkAssignment.h"
#include "squawk/SquawkEventHandler.h"
#include "squawk/SquawkGenerator.h"
#include "controller/ControllerPositionCollection.h"
#include "intention/SectorExitRepository.h"
#include "message/UserMessager.h"
#include "euroscope/UserSetting.h"
#include "command/CommandHandlerCollection.h"
#include "login/Login.h"
#include "hold/HoldManager.h"
#include "euroscope/UserSettingAwareCollection.h"
#include "hold/HoldSelectionMenu.h"
#include "dialog/DialogManager.h"
#include "hold/HoldDisplayFactory.h"
#include "setting/SettingRepository.h"
#include "countdown/TimerConfigurationManager.h"
#include "datablock/DisplayTime.h"
#include "push/PushEventProcessorCollection.h"
#include "euroscope/RunwayDialogAwareCollection.h"
#include "sectorfile/RunwayCollection.h"
#include "handoff/HandoffCollection.h"
#include "regional/RegionalPressureManager.h"
#include "navaids/NavaidCollection.h"
#include "hold/PublishedHoldCollection.h"
#include "controller/HandoffEventHandlerCollection.h"
#include "integration/ExternalMessageEventHandler.h"
#include "sid/SidCollection.h"

namespace UKControllerPlugin::Bootstrap {
    PersistenceContainer::~PersistenceContainer() = default;
    PersistenceContainer::PersistenceContainer(PersistenceContainer&&) noexcept = default;
    auto PersistenceContainer::operator=(PersistenceContainer&&)  noexcept -> PersistenceContainer& = default;
} // namespace UKControllerPlugin::Bootstrap
